name: "Restore previous run result"
description: "Restore the previous run result for a particular job"

inputs:
  action:
    description: 'The action to perform (`restore_result` - get the previous result, `record_result` - record the result)
    required: true

outputs:
  run-result:
    description: "Previous run result"
    value: ${{ steps.run_result.outputs.run_result }}

runs:
  using: "composite"
  steps:
    - id: timestamp
      if: ${{ inputs.action == 'restore_result' }}
      shell: bash
      run: echo "::set-output name=timestamp::$(date +'%Y-%m-%dT%H:%M:%S')"

    - name: Restore the previous run result
      if: ${{ inputs.action == 'restore_result' }}
      uses: actions/cache@v2
      with:
        path: |
          run_result
        key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
        restore-keys: |
          ${{ github.run_id }}-${{ github.job }}-
          
    - name: Get the previous run result
      if: ${{ inputs.action == 'restore_result' }}
      id: run_result
      shell: bash
      run: echo "::set-output name=run_result::$(cat run_result 2>/dev/null || echo 'default')"
      
      
     - name: Record result
      if: ${{ inputs.action == 'record_result' }}
      shell: bash
      run: echo 'success' > run_result
